### ISSUE TITLE
Make Indicator more static(reserve space)

### ISSUE THREAD

**Issue by jee-r** [prateekmedia/netspeedsimplified#8]
Hi,

Is it possible to add an option or natively reserved space for network speed infos to avoid that the plugin block is resized every refresh. if my explanation it's not very clear i drew a diagram 

![Untitled Diagram](https://user-images.githubusercontent.com/10530469/100218077-86a8e880-2f14-11eb-8915-fd9cf6735f70.png)

**Comment by prateekmedia** [comment]
Do you mean something like this

↑    5.0 MB/s
↑  50.0    B/s
↑150.0 KB/s

Yes it can be done will see I thought it will be cleaner if its 150 rather than 150.0 but yes I will see that.

**Comment by jee-r** [comment]
Thank you for you answer @prateekmedia sorry in the diagram i forget the case whent we have floating number

yes the idea is to have a fixed size for number  and  speed unit  like  this :
```
↑   5.0  MB/s
↑  50.0   B/s
↑ 150.0  KB/s
```
in the example below i represente 'reserved space' by underscore
```
[↑] [__5.0] [MB/s]
[↑] [_50.0] [_B/s]
[↑] [150.0] [KB/s]

[↑] [ _ _ _ . _ ] [ _ _/s ] #( i've added space between underscore for readability)
```

**Comment by prateekmedia** [comment]
Ok it's clear, will do it in the next release of v21 on extensions.gnome.org till then stay updated by starring the repo or marking it as watch

**Comment by prateekmedia** [comment]
Fixed in latest Commit (f407f3997c1b7720d816be89f5bf933d7520dc08) , you can test then I will close this.

NOTE that It is not implemented for mode 5 or in simple words for total downloads indicator & I also have not left space for [K] or other prefix of B as it will take extra space

**Comment by m0hithreddy** [comment]
Hey, that was already fixed in the latest updates even before this commit. Yes, it used to be an annoying thing, every other extension pushed aside at each refresh. It was solved by giving a fixed value for the width attribute in the stylesheet or by giving an adequate min-width attribute. But all the text is left-aligned. But as @jee-r asked he wants speed to be right-aligned and unit to be right-aligned individually which is mostly a personal preference, and it is good to have it as an option in the preference menu

**Comment by m0hithreddy** [comment]
And the current solution doesn't seem to work for every case. I just found one. 
![Screenshot from 2020-11-25 21-52-08](https://user-images.githubusercontent.com/24791724/100254972-f1840f00-2f68-11eb-9e02-f8175fb1b494.png)

**Comment by prateekmedia** [comment]
@m0hithreddy Tried to fix it in b6206f88b39ae3cf1f4ff5ff74a76a3a6aa57585

**Comment by m0hithreddy** [comment]
![Screenshot from 2020-11-25 23-56-53](https://user-images.githubusercontent.com/24791724/100267843-1df45700-2f7a-11eb-83a7-f2d0d04c03cc.png)

Still doesn't seem to work,, Update from my side, I approached the issue in terms of padding the space and making the string the same length every time, it didn't work... Mostly because each character is occupying a different space.

**Comment by prateekmedia** [comment]
@m0hithreddy you are right but it is the closest that I can get for this type of look, I will find if their exist any other way for this

**Comment by m0hithreddy** [comment]
Give me some time... I think I know a way. let me try.

**Comment by m0hithreddy** [comment]
#9 This PR should fix.

**Comment by prateekmedia** [comment]
This PR #10 may fix it, as it include separate icon indicators, you can test it by downloading zip and running 
```
make install
``` 
inside the folder

If theirs any other issue or problem you can reopen this issue or register a new one.. :)
